num = int(input())
f_digit = num // 100
s_digit = num // 10 % 10
t_digit = num % 10
print(f_digit + s_digit + t_digit)num = int(input())
next_num = num + 1
prev_num = num - 1
print("The next number for the number", num, "is", next_num, end=".\n")
print("The previous number for the number", num, "is", prev_num, end=".\n")
